/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoomId = IDL.Nat;
export const MessageId = IDL.Nat;
export const PostId = IDL.Nat;
export const AudioContent = IDL.Record({
  'url' : IDL.Text,
  'duration' : IDL.Opt(IDL.Nat),
  'mimeType' : IDL.Text,
  'fileSize' : IDL.Nat,
});
export const VideoContent = IDL.Record({
  'url' : IDL.Text,
  'duration' : IDL.Opt(IDL.Nat),
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'mimeType' : IDL.Text,
  'fileSize' : IDL.Nat,
});
export const LinkContent = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const ImageContent = IDL.Record({
  'url' : IDL.Text,
  'height' : IDL.Opt(IDL.Nat),
  'mimeType' : IDL.Text,
  'fileSize' : IDL.Nat,
  'width' : IDL.Opt(IDL.Nat),
});
export const MessageContent = IDL.Variant({
  'deleted' : IDL.Null,
  'audio' : AudioContent,
  'video' : VideoContent,
  'link' : LinkContent,
  'text' : IDL.Text,
  'image' : ImageContent,
});
export const SendFeedMediaInput = IDL.Record({
  'parentPostId' : IDL.Opt(PostId),
  'content' : MessageContent,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Post = IDL.Record({
  'id' : PostId,
  'parentPostId' : IDL.Opt(PostId),
  'content' : MessageContent,
  'likedBy' : IDL.Vec(UserId),
  'author' : UserId,
  'pinned' : IDL.Bool,
  'timestamp' : Timestamp,
  'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(UserId))),
});
export const CatalogRoom = IDL.Record({
  'id' : RoomId,
  'coverImageUrl' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'creator' : UserId,
  'members' : IDL.Vec(UserId),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'messageCount' : IDL.Nat,
  'lastActivityAt' : Timestamp,
});
export const ConversationId = IDL.Nat;
export const ConversationKind = IDL.Variant({
  'group' : IDL.Record({ 'name' : IDL.Text }),
  'direct' : IDL.Null,
});
export const ConversationSummary = IDL.Record({
  'id' : ConversationId,
  'members' : IDL.Vec(UserId),
  'lastMessageAt' : IDL.Opt(Timestamp),
  'kind' : ConversationKind,
  'unreadCount' : IDL.Nat,
});
export const CatalogMessage = IDL.Record({
  'id' : MessageId,
  'deleted' : IDL.Bool,
  'content' : MessageContent,
  'createdAt' : Timestamp,
  'author' : UserId,
  'pinned' : IDL.Bool,
  'roomId' : RoomId,
  'editedAt' : IDL.Opt(Timestamp),
  'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(UserId))),
});
export const EditEntry = IDL.Record({
  'editedAt' : Timestamp,
  'previousContent' : MessageContent,
});
export const FeedPage = IDL.Record({
  'total' : IDL.Nat,
  'posts' : IDL.Vec(Post),
});
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : MessageContent,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'conversationId' : ConversationId,
});
export const MessagePage = IDL.Record({
  'messages' : IDL.Vec(Message),
  'nextCursor' : IDL.Opt(MessageId),
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Text,
  'lastHandleChange' : IDL.Opt(IDL.Int),
  'registeredAt' : Timestamp,
  'usernameHandle' : IDL.Opt(IDL.Text),
  'profileImageUrl' : IDL.Opt(IDL.Text),
});
export const PinnedMessage = IDL.Record({
  'messageId' : MessageId,
  'conversationId' : ConversationId,
  'message' : Message,
  'pinnedAt' : Timestamp,
  'pinnedBy' : UserId,
});
export const ReactionGroup = IDL.Record({
  'count' : IDL.Nat,
  'userIds' : IDL.Vec(UserId),
  'emoji' : IDL.Text,
});
export const SearchResult = IDL.Record({
  'messageId' : MessageId,
  'snippet' : IDL.Text,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'conversationId' : ConversationId,
});
export const SendCatalogMediaInput = IDL.Record({
  'content' : MessageContent,
  'roomId' : RoomId,
});
export const SendMessageInput = IDL.Record({
  'content' : MessageContent,
  'conversationId' : IDL.Nat,
});
export const UpdateProfileRequest = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Opt(IDL.Text),
  'usernameHandle' : IDL.Opt(IDL.Text),
  'profileImageUrl' : IDL.Opt(IDL.Text),
});
export const UpdateProfileResult = IDL.Variant({
  'ok' : UserProfile,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageCreateCertificate' : IDL.Func([IDL.Text], [], []),
  'addCatalogReaction' : IDL.Func([RoomId, MessageId, IDL.Text], [], []),
  'addFeedReaction' : IDL.Func([PostId, IDL.Text], [], []),
  'addReaction' : IDL.Func([MessageId, IDL.Text], [], []),
  'addReply' : IDL.Func([PostId, SendFeedMediaInput], [Post], []),
  'createCatalogRoom' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [CatalogRoom],
      [],
    ),
  'createDirectConversation' : IDL.Func([UserId], [ConversationSummary], []),
  'createGroupConversation' : IDL.Func(
      [IDL.Text, IDL.Vec(UserId)],
      [ConversationSummary],
      [],
    ),
  'createPost' : IDL.Func([SendFeedMediaInput], [Post], []),
  'deleteCatalogMessage' : IDL.Func([RoomId, MessageId], [], []),
  'deleteMessage' : IDL.Func([MessageId], [IDL.Bool], []),
  'deletePost' : IDL.Func([PostId], [], []),
  'editCatalogMessage' : IDL.Func([RoomId, MessageId, IDL.Text], [], []),
  'editMessage' : IDL.Func([MessageId, MessageContent], [], []),
  'getCatalogMessages' : IDL.Func(
      [RoomId, IDL.Opt(MessageId)],
      [IDL.Vec(CatalogMessage)],
      ['query'],
    ),
  'getCatalogRoom' : IDL.Func([RoomId], [IDL.Opt(CatalogRoom)], ['query']),
  'getCatalogRooms' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(CatalogRoom)],
      ['query'],
    ),
  'getCatalogTypingUsers' : IDL.Func([RoomId], [IDL.Vec(UserId)], ['query']),
  'getConversation' : IDL.Func(
      [ConversationId],
      [IDL.Opt(ConversationSummary)],
      ['query'],
    ),
  'getEditHistory' : IDL.Func([MessageId], [IDL.Vec(EditEntry)], ['query']),
  'getFeedPosts' : IDL.Func([IDL.Nat, IDL.Nat], [FeedPage], ['query']),
  'getFeedTypingUsers' : IDL.Func([PostId], [IDL.Vec(UserId)], ['query']),
  'getJoinedCatalogRooms' : IDL.Func([], [IDL.Vec(CatalogRoom)], ['query']),
  'getMessages' : IDL.Func(
      [ConversationId, IDL.Opt(MessageId), IDL.Nat],
      [MessagePage],
      ['query'],
    ),
  'getOrCreateProfile' : IDL.Func([IDL.Text], [UserProfile], []),
  'getPinnedCatalogMessages' : IDL.Func(
      [RoomId],
      [IDL.Vec(CatalogMessage)],
      ['query'],
    ),
  'getPinnedFeedReplies' : IDL.Func([PostId], [IDL.Vec(Post)], ['query']),
  'getPinnedMessages' : IDL.Func(
      [ConversationId],
      [IDL.Vec(PinnedMessage)],
      ['query'],
    ),
  'getPostLikes' : IDL.Func([PostId], [IDL.Vec(UserId)], ['query']),
  'getPostReplies' : IDL.Func([PostId], [IDL.Vec(Post)], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getReactions' : IDL.Func([MessageId], [IDL.Vec(ReactionGroup)], ['query']),
  'getSharedConversations' : IDL.Func(
      [UserId],
      [IDL.Vec(ConversationSummary)],
      ['query'],
    ),
  'getTypingUsers' : IDL.Func(
      [ConversationId],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getUnreadCatalogCount' : IDL.Func([RoomId], [IDL.Nat], ['query']),
  'getUnreadFeedCount' : IDL.Func([], [IDL.Nat], []),
  'joinCatalogRoom' : IDL.Func([RoomId], [], []),
  'leaveCatalogRoom' : IDL.Func([RoomId], [], []),
  'likePost' : IDL.Func([PostId], [], []),
  'listConversations' : IDL.Func([], [IDL.Vec(ConversationSummary)], ['query']),
  'markCatalogRoomRead' : IDL.Func([RoomId], [], []),
  'markConversationRead' : IDL.Func([ConversationId], [], []),
  'markFeedRead' : IDL.Func([], [], []),
  'pinCatalogMessage' : IDL.Func([RoomId, MessageId], [], []),
  'pinFeedReply' : IDL.Func([PostId, PostId], [], []),
  'pinMessage' : IDL.Func([MessageId], [], []),
  'removeCatalogReaction' : IDL.Func([RoomId, MessageId, IDL.Text], [], []),
  'removeFeedReaction' : IDL.Func([PostId, IDL.Text], [], []),
  'removeReaction' : IDL.Func([MessageId], [], []),
  'removeUserFromCatalogRoom' : IDL.Func([RoomId, IDL.Principal], [], []),
  'reportCatalogRoom' : IDL.Func([RoomId, IDL.Text], [], []),
  'searchMessages' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
  'sendCatalogMediaMessage' : IDL.Func(
      [SendCatalogMediaInput],
      [CatalogMessage],
      [],
    ),
  'sendMediaMessage' : IDL.Func([SendMessageInput], [Message], []),
  'sendMessage' : IDL.Func([ConversationId, IDL.Text], [Message], []),
  'setCatalogTyping' : IDL.Func([RoomId], [], []),
  'setFeedTyping' : IDL.Func([PostId], [], []),
  'setTyping' : IDL.Func([ConversationId, IDL.Bool], [], []),
  'unlikePost' : IDL.Func([PostId], [], []),
  'unpinCatalogMessage' : IDL.Func([RoomId, MessageId], [], []),
  'unpinFeedReply' : IDL.Func([PostId, PostId], [], []),
  'unpinMessage' : IDL.Func([MessageId], [], []),
  'updateProfile' : IDL.Func([UpdateProfileRequest], [UpdateProfileResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoomId = IDL.Nat;
  const MessageId = IDL.Nat;
  const PostId = IDL.Nat;
  const AudioContent = IDL.Record({
    'url' : IDL.Text,
    'duration' : IDL.Opt(IDL.Nat),
    'mimeType' : IDL.Text,
    'fileSize' : IDL.Nat,
  });
  const VideoContent = IDL.Record({
    'url' : IDL.Text,
    'duration' : IDL.Opt(IDL.Nat),
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'mimeType' : IDL.Text,
    'fileSize' : IDL.Nat,
  });
  const LinkContent = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const ImageContent = IDL.Record({
    'url' : IDL.Text,
    'height' : IDL.Opt(IDL.Nat),
    'mimeType' : IDL.Text,
    'fileSize' : IDL.Nat,
    'width' : IDL.Opt(IDL.Nat),
  });
  const MessageContent = IDL.Variant({
    'deleted' : IDL.Null,
    'audio' : AudioContent,
    'video' : VideoContent,
    'link' : LinkContent,
    'text' : IDL.Text,
    'image' : ImageContent,
  });
  const SendFeedMediaInput = IDL.Record({
    'parentPostId' : IDL.Opt(PostId),
    'content' : MessageContent,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Post = IDL.Record({
    'id' : PostId,
    'parentPostId' : IDL.Opt(PostId),
    'content' : MessageContent,
    'likedBy' : IDL.Vec(UserId),
    'author' : UserId,
    'pinned' : IDL.Bool,
    'timestamp' : Timestamp,
    'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(UserId))),
  });
  const CatalogRoom = IDL.Record({
    'id' : RoomId,
    'coverImageUrl' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'creator' : UserId,
    'members' : IDL.Vec(UserId),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'messageCount' : IDL.Nat,
    'lastActivityAt' : Timestamp,
  });
  const ConversationId = IDL.Nat;
  const ConversationKind = IDL.Variant({
    'group' : IDL.Record({ 'name' : IDL.Text }),
    'direct' : IDL.Null,
  });
  const ConversationSummary = IDL.Record({
    'id' : ConversationId,
    'members' : IDL.Vec(UserId),
    'lastMessageAt' : IDL.Opt(Timestamp),
    'kind' : ConversationKind,
    'unreadCount' : IDL.Nat,
  });
  const CatalogMessage = IDL.Record({
    'id' : MessageId,
    'deleted' : IDL.Bool,
    'content' : MessageContent,
    'createdAt' : Timestamp,
    'author' : UserId,
    'pinned' : IDL.Bool,
    'roomId' : RoomId,
    'editedAt' : IDL.Opt(Timestamp),
    'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(UserId))),
  });
  const EditEntry = IDL.Record({
    'editedAt' : Timestamp,
    'previousContent' : MessageContent,
  });
  const FeedPage = IDL.Record({ 'total' : IDL.Nat, 'posts' : IDL.Vec(Post) });
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : MessageContent,
    'sender' : UserId,
    'sentAt' : Timestamp,
    'conversationId' : ConversationId,
  });
  const MessagePage = IDL.Record({
    'messages' : IDL.Vec(Message),
    'nextCursor' : IDL.Opt(MessageId),
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Text,
    'lastHandleChange' : IDL.Opt(IDL.Int),
    'registeredAt' : Timestamp,
    'usernameHandle' : IDL.Opt(IDL.Text),
    'profileImageUrl' : IDL.Opt(IDL.Text),
  });
  const PinnedMessage = IDL.Record({
    'messageId' : MessageId,
    'conversationId' : ConversationId,
    'message' : Message,
    'pinnedAt' : Timestamp,
    'pinnedBy' : UserId,
  });
  const ReactionGroup = IDL.Record({
    'count' : IDL.Nat,
    'userIds' : IDL.Vec(UserId),
    'emoji' : IDL.Text,
  });
  const SearchResult = IDL.Record({
    'messageId' : MessageId,
    'snippet' : IDL.Text,
    'sender' : UserId,
    'sentAt' : Timestamp,
    'conversationId' : ConversationId,
  });
  const SendCatalogMediaInput = IDL.Record({
    'content' : MessageContent,
    'roomId' : RoomId,
  });
  const SendMessageInput = IDL.Record({
    'content' : MessageContent,
    'conversationId' : IDL.Nat,
  });
  const UpdateProfileRequest = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Opt(IDL.Text),
    'usernameHandle' : IDL.Opt(IDL.Text),
    'profileImageUrl' : IDL.Opt(IDL.Text),
  });
  const UpdateProfileResult = IDL.Variant({
    'ok' : UserProfile,
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageCreateCertificate' : IDL.Func([IDL.Text], [], []),
    'addCatalogReaction' : IDL.Func([RoomId, MessageId, IDL.Text], [], []),
    'addFeedReaction' : IDL.Func([PostId, IDL.Text], [], []),
    'addReaction' : IDL.Func([MessageId, IDL.Text], [], []),
    'addReply' : IDL.Func([PostId, SendFeedMediaInput], [Post], []),
    'createCatalogRoom' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [CatalogRoom],
        [],
      ),
    'createDirectConversation' : IDL.Func([UserId], [ConversationSummary], []),
    'createGroupConversation' : IDL.Func(
        [IDL.Text, IDL.Vec(UserId)],
        [ConversationSummary],
        [],
      ),
    'createPost' : IDL.Func([SendFeedMediaInput], [Post], []),
    'deleteCatalogMessage' : IDL.Func([RoomId, MessageId], [], []),
    'deleteMessage' : IDL.Func([MessageId], [IDL.Bool], []),
    'deletePost' : IDL.Func([PostId], [], []),
    'editCatalogMessage' : IDL.Func([RoomId, MessageId, IDL.Text], [], []),
    'editMessage' : IDL.Func([MessageId, MessageContent], [], []),
    'getCatalogMessages' : IDL.Func(
        [RoomId, IDL.Opt(MessageId)],
        [IDL.Vec(CatalogMessage)],
        ['query'],
      ),
    'getCatalogRoom' : IDL.Func([RoomId], [IDL.Opt(CatalogRoom)], ['query']),
    'getCatalogRooms' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(CatalogRoom)],
        ['query'],
      ),
    'getCatalogTypingUsers' : IDL.Func([RoomId], [IDL.Vec(UserId)], ['query']),
    'getConversation' : IDL.Func(
        [ConversationId],
        [IDL.Opt(ConversationSummary)],
        ['query'],
      ),
    'getEditHistory' : IDL.Func([MessageId], [IDL.Vec(EditEntry)], ['query']),
    'getFeedPosts' : IDL.Func([IDL.Nat, IDL.Nat], [FeedPage], ['query']),
    'getFeedTypingUsers' : IDL.Func([PostId], [IDL.Vec(UserId)], ['query']),
    'getJoinedCatalogRooms' : IDL.Func([], [IDL.Vec(CatalogRoom)], ['query']),
    'getMessages' : IDL.Func(
        [ConversationId, IDL.Opt(MessageId), IDL.Nat],
        [MessagePage],
        ['query'],
      ),
    'getOrCreateProfile' : IDL.Func([IDL.Text], [UserProfile], []),
    'getPinnedCatalogMessages' : IDL.Func(
        [RoomId],
        [IDL.Vec(CatalogMessage)],
        ['query'],
      ),
    'getPinnedFeedReplies' : IDL.Func([PostId], [IDL.Vec(Post)], ['query']),
    'getPinnedMessages' : IDL.Func(
        [ConversationId],
        [IDL.Vec(PinnedMessage)],
        ['query'],
      ),
    'getPostLikes' : IDL.Func([PostId], [IDL.Vec(UserId)], ['query']),
    'getPostReplies' : IDL.Func([PostId], [IDL.Vec(Post)], ['query']),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getReactions' : IDL.Func([MessageId], [IDL.Vec(ReactionGroup)], ['query']),
    'getSharedConversations' : IDL.Func(
        [UserId],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'getTypingUsers' : IDL.Func(
        [ConversationId],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getUnreadCatalogCount' : IDL.Func([RoomId], [IDL.Nat], ['query']),
    'getUnreadFeedCount' : IDL.Func([], [IDL.Nat], []),
    'joinCatalogRoom' : IDL.Func([RoomId], [], []),
    'leaveCatalogRoom' : IDL.Func([RoomId], [], []),
    'likePost' : IDL.Func([PostId], [], []),
    'listConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'markCatalogRoomRead' : IDL.Func([RoomId], [], []),
    'markConversationRead' : IDL.Func([ConversationId], [], []),
    'markFeedRead' : IDL.Func([], [], []),
    'pinCatalogMessage' : IDL.Func([RoomId, MessageId], [], []),
    'pinFeedReply' : IDL.Func([PostId, PostId], [], []),
    'pinMessage' : IDL.Func([MessageId], [], []),
    'removeCatalogReaction' : IDL.Func([RoomId, MessageId, IDL.Text], [], []),
    'removeFeedReaction' : IDL.Func([PostId, IDL.Text], [], []),
    'removeReaction' : IDL.Func([MessageId], [], []),
    'removeUserFromCatalogRoom' : IDL.Func([RoomId, IDL.Principal], [], []),
    'reportCatalogRoom' : IDL.Func([RoomId, IDL.Text], [], []),
    'searchMessages' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
    'sendCatalogMediaMessage' : IDL.Func(
        [SendCatalogMediaInput],
        [CatalogMessage],
        [],
      ),
    'sendMediaMessage' : IDL.Func([SendMessageInput], [Message], []),
    'sendMessage' : IDL.Func([ConversationId, IDL.Text], [Message], []),
    'setCatalogTyping' : IDL.Func([RoomId], [], []),
    'setFeedTyping' : IDL.Func([PostId], [], []),
    'setTyping' : IDL.Func([ConversationId, IDL.Bool], [], []),
    'unlikePost' : IDL.Func([PostId], [], []),
    'unpinCatalogMessage' : IDL.Func([RoomId, MessageId], [], []),
    'unpinFeedReply' : IDL.Func([PostId, PostId], [], []),
    'unpinMessage' : IDL.Func([MessageId], [], []),
    'updateProfile' : IDL.Func(
        [UpdateProfileRequest],
        [UpdateProfileResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };