/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AudioContent {
  'url' : string,
  'duration' : [] | [bigint],
  'mimeType' : string,
  'fileSize' : bigint,
}
export interface CatalogMessage {
  'id' : MessageId,
  'deleted' : boolean,
  'content' : MessageContent,
  'createdAt' : Timestamp,
  'author' : UserId,
  'pinned' : boolean,
  'roomId' : RoomId,
  'editedAt' : [] | [Timestamp],
  'reactions' : Array<[string, Array<UserId>]>,
}
export interface CatalogRoom {
  'id' : RoomId,
  'coverImageUrl' : [] | [string],
  'title' : string,
  'creator' : UserId,
  'members' : Array<UserId>,
  'createdAt' : Timestamp,
  'description' : string,
  'messageCount' : bigint,
  'lastActivityAt' : Timestamp,
}
export type ConversationId = bigint;
export type ConversationKind = { 'group' : { 'name' : string } } |
  { 'direct' : null };
export interface ConversationSummary {
  'id' : ConversationId,
  'members' : Array<UserId>,
  'lastMessageAt' : [] | [Timestamp],
  'kind' : ConversationKind,
  'unreadCount' : bigint,
}
export interface EditEntry {
  'editedAt' : Timestamp,
  'previousContent' : MessageContent,
}
export interface FeedPage { 'total' : bigint, 'posts' : Array<Post> }
export interface ImageContent {
  'url' : string,
  'height' : [] | [bigint],
  'mimeType' : string,
  'fileSize' : bigint,
  'width' : [] | [bigint],
}
export interface LinkContent {
  'url' : string,
  'title' : [] | [string],
  'description' : [] | [string],
  'imageUrl' : [] | [string],
}
export interface Message {
  'id' : MessageId,
  'content' : MessageContent,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'conversationId' : ConversationId,
}
export type MessageContent = { 'deleted' : null } |
  { 'audio' : AudioContent } |
  { 'video' : VideoContent } |
  { 'link' : LinkContent } |
  { 'text' : string } |
  { 'image' : ImageContent };
export type MessageId = bigint;
export interface MessagePage {
  'messages' : Array<Message>,
  'nextCursor' : [] | [MessageId],
}
export interface PinnedMessage {
  'messageId' : MessageId,
  'conversationId' : ConversationId,
  'message' : Message,
  'pinnedAt' : Timestamp,
  'pinnedBy' : UserId,
}
export interface Post {
  'id' : PostId,
  'parentPostId' : [] | [PostId],
  'content' : MessageContent,
  'likedBy' : Array<UserId>,
  'author' : UserId,
  'pinned' : boolean,
  'timestamp' : Timestamp,
  'reactions' : Array<[string, Array<UserId>]>,
}
export type PostId = bigint;
export interface ReactionGroup {
  'count' : bigint,
  'userIds' : Array<UserId>,
  'emoji' : string,
}
export type RoomId = bigint;
export interface SearchResult {
  'messageId' : MessageId,
  'snippet' : string,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'conversationId' : ConversationId,
}
export interface SendCatalogMediaInput {
  'content' : MessageContent,
  'roomId' : RoomId,
}
export interface SendFeedMediaInput {
  'parentPostId' : [] | [PostId],
  'content' : MessageContent,
}
export interface SendMessageInput {
  'content' : MessageContent,
  'conversationId' : bigint,
}
export type Timestamp = bigint;
export interface UpdateProfileRequest {
  'bio' : [] | [string],
  'displayName' : [] | [string],
  'usernameHandle' : [] | [string],
  'profileImageUrl' : [] | [string],
}
export type UpdateProfileResult = { 'ok' : UserProfile } |
  { 'err' : string };
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : [] | [string],
  'displayName' : string,
  'lastHandleChange' : [] | [bigint],
  'registeredAt' : Timestamp,
  'usernameHandle' : [] | [string],
  'profileImageUrl' : [] | [string],
}
export interface VideoContent {
  'url' : string,
  'duration' : [] | [bigint],
  'thumbnailUrl' : [] | [string],
  'mimeType' : string,
  'fileSize' : bigint,
}
export interface _SERVICE {
  'addCatalogReaction' : ActorMethod<[RoomId, MessageId, string], undefined>,
  'addFeedReaction' : ActorMethod<[PostId, string], undefined>,
  'addReaction' : ActorMethod<[MessageId, string], undefined>,
  'addReply' : ActorMethod<[PostId, SendFeedMediaInput], Post>,
  'createCatalogRoom' : ActorMethod<
    [string, string, [] | [string]],
    CatalogRoom
  >,
  'createDirectConversation' : ActorMethod<[UserId], ConversationSummary>,
  'createGroupConversation' : ActorMethod<
    [string, Array<UserId>],
    ConversationSummary
  >,
  'createPost' : ActorMethod<[SendFeedMediaInput], Post>,
  'deleteCatalogMessage' : ActorMethod<[RoomId, MessageId], undefined>,
  'deleteMessage' : ActorMethod<[MessageId], boolean>,
  'deletePost' : ActorMethod<[PostId], undefined>,
  'editCatalogMessage' : ActorMethod<[RoomId, MessageId, string], undefined>,
  'editMessage' : ActorMethod<[MessageId, MessageContent], undefined>,
  'getCatalogMessages' : ActorMethod<
    [RoomId, [] | [MessageId]],
    Array<CatalogMessage>
  >,
  'getCatalogRoom' : ActorMethod<[RoomId], [] | [CatalogRoom]>,
  'getCatalogRooms' : ActorMethod<[[] | [string]], Array<CatalogRoom>>,
  'getCatalogTypingUsers' : ActorMethod<[RoomId], Array<UserId>>,
  'getConversation' : ActorMethod<[ConversationId], [] | [ConversationSummary]>,
  'getEditHistory' : ActorMethod<[MessageId], Array<EditEntry>>,
  'getFeedPosts' : ActorMethod<[bigint, bigint], FeedPage>,
  'getFeedTypingUsers' : ActorMethod<[PostId], Array<UserId>>,
  'getJoinedCatalogRooms' : ActorMethod<[], Array<CatalogRoom>>,
  'getMessages' : ActorMethod<
    [ConversationId, [] | [MessageId], bigint],
    MessagePage
  >,
  'getOrCreateProfile' : ActorMethod<[string], UserProfile>,
  'getPinnedCatalogMessages' : ActorMethod<[RoomId], Array<CatalogMessage>>,
  'getPinnedFeedReplies' : ActorMethod<[PostId], Array<Post>>,
  'getPinnedMessages' : ActorMethod<[ConversationId], Array<PinnedMessage>>,
  'getPostLikes' : ActorMethod<[PostId], Array<UserId>>,
  'getPostReplies' : ActorMethod<[PostId], Array<Post>>,
  'getProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getReactions' : ActorMethod<[MessageId], Array<ReactionGroup>>,
  'getSharedConversations' : ActorMethod<[UserId], Array<ConversationSummary>>,
  'getTypingUsers' : ActorMethod<[ConversationId], Array<UserProfile>>,
  'getUnreadCatalogCount' : ActorMethod<[RoomId], bigint>,
  'getUnreadFeedCount' : ActorMethod<[], bigint>,
  'joinCatalogRoom' : ActorMethod<[RoomId], undefined>,
  'leaveCatalogRoom' : ActorMethod<[RoomId], undefined>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'listConversations' : ActorMethod<[], Array<ConversationSummary>>,
  'markCatalogRoomRead' : ActorMethod<[RoomId], undefined>,
  'markConversationRead' : ActorMethod<[ConversationId], undefined>,
  'markFeedRead' : ActorMethod<[], undefined>,
  'pinCatalogMessage' : ActorMethod<[RoomId, MessageId], undefined>,
  'pinFeedReply' : ActorMethod<[PostId, PostId], undefined>,
  'pinMessage' : ActorMethod<[MessageId], undefined>,
  'removeCatalogReaction' : ActorMethod<[RoomId, MessageId, string], undefined>,
  'removeFeedReaction' : ActorMethod<[PostId, string], undefined>,
  'removeReaction' : ActorMethod<[MessageId], undefined>,
  'removeUserFromCatalogRoom' : ActorMethod<[RoomId, Principal], undefined>,
  'reportCatalogRoom' : ActorMethod<[RoomId, string], undefined>,
  'searchMessages' : ActorMethod<[string], Array<SearchResult>>,
  'sendCatalogMediaMessage' : ActorMethod<
    [SendCatalogMediaInput],
    CatalogMessage
  >,
  'sendMediaMessage' : ActorMethod<[SendMessageInput], Message>,
  'sendMessage' : ActorMethod<[ConversationId, string], Message>,
  'setCatalogTyping' : ActorMethod<[RoomId], undefined>,
  'setFeedTyping' : ActorMethod<[PostId], undefined>,
  'setTyping' : ActorMethod<[ConversationId, boolean], undefined>,
  'unlikePost' : ActorMethod<[PostId], undefined>,
  'unpinCatalogMessage' : ActorMethod<[RoomId, MessageId], undefined>,
  'unpinFeedReply' : ActorMethod<[PostId, PostId], undefined>,
  'unpinMessage' : ActorMethod<[MessageId], undefined>,
  'updateProfile' : ActorMethod<[UpdateProfileRequest], UpdateProfileResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];