/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VideoContent {
    url: string;
    duration?: bigint;
    thumbnailUrl?: string;
    mimeType: string;
    fileSize: bigint;
}
export type Timestamp = bigint;
export interface SearchResult {
    messageId: MessageId;
    snippet: string;
    sender: UserId;
    sentAt: Timestamp;
    conversationId: ConversationId;
}
export type PostId = bigint;
export interface SendFeedMediaInput {
    parentPostId?: PostId;
    content: MessageContent;
}
export interface AudioContent {
    url: string;
    duration?: bigint;
    mimeType: string;
    fileSize: bigint;
}
export type RoomId = bigint;
export type MessageContent = {
    __kind__: "deleted";
    deleted: null;
} | {
    __kind__: "audio";
    audio: AudioContent;
} | {
    __kind__: "video";
    video: VideoContent;
} | {
    __kind__: "link";
    link: LinkContent;
} | {
    __kind__: "text";
    text: string;
} | {
    __kind__: "image";
    image: ImageContent;
};
export type ConversationId = bigint;
export interface UpdateProfileRequest {
    bio?: string;
    displayName?: string;
    usernameHandle?: string;
    profileImageUrl?: string;
}
export interface Post {
    id: PostId;
    parentPostId?: PostId;
    content: MessageContent;
    likedBy: Array<UserId>;
    author: UserId;
    pinned: boolean;
    timestamp: Timestamp;
    reactions: Array<[string, Array<UserId>]>;
}
export interface CatalogRoom {
    id: RoomId;
    coverImageUrl?: string;
    title: string;
    creator: UserId;
    members: Array<UserId>;
    createdAt: Timestamp;
    description: string;
    messageCount: bigint;
    lastActivityAt: Timestamp;
}
export interface CatalogMessage {
    id: MessageId;
    deleted: boolean;
    content: MessageContent;
    createdAt: Timestamp;
    author: UserId;
    pinned: boolean;
    roomId: RoomId;
    editedAt?: Timestamp;
    reactions: Array<[string, Array<UserId>]>;
}
export interface ConversationSummary {
    id: ConversationId;
    members: Array<UserId>;
    lastMessageAt?: Timestamp;
    kind: ConversationKind;
    unreadCount: bigint;
}
export interface SendMessageInput {
    content: MessageContent;
    conversationId: bigint;
}
export interface PinnedMessage {
    messageId: MessageId;
    conversationId: ConversationId;
    message: Message;
    pinnedAt: Timestamp;
    pinnedBy: UserId;
}
export interface LinkContent {
    url: string;
    title?: string;
    description?: string;
    imageUrl?: string;
}
export interface EditEntry {
    editedAt: Timestamp;
    previousContent: MessageContent;
}
export type ConversationKind = {
    __kind__: "group";
    group: {
        name: string;
    };
} | {
    __kind__: "direct";
    direct: null;
};
export interface ImageContent {
    url: string;
    height?: bigint;
    mimeType: string;
    fileSize: bigint;
    width?: bigint;
}
export type UserId = Principal;
export interface FeedPage {
    total: bigint;
    posts: Array<Post>;
}
export type MessageId = bigint;
export interface SendCatalogMediaInput {
    content: MessageContent;
    roomId: RoomId;
}
export interface Message {
    id: MessageId;
    content: MessageContent;
    sender: UserId;
    sentAt: Timestamp;
    conversationId: ConversationId;
}
export interface ReactionGroup {
    count: bigint;
    userIds: Array<UserId>;
    emoji: string;
}
export type UpdateProfileResult = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
};
export interface MessagePage {
    messages: Array<Message>;
    nextCursor?: MessageId;
}
export interface UserProfile {
    id: UserId;
    bio?: string;
    displayName: string;
    lastHandleChange?: bigint;
    registeredAt: Timestamp;
    usernameHandle?: string;
    profileImageUrl?: string;
}
export interface backendInterface {
    /**
     * / Called by the frontend StorageClient before every upload.
     * / Stores the file hash in certified data; the IC attaches the certificate
     * / to the update-call response so the storage gateway can verify it.
     */
    _immutableObjectStorageCreateCertificate(hashWithPrefix: string): Promise<void>;
    addCatalogReaction(roomId: RoomId, messageId: MessageId, emoji: string): Promise<void>;
    addFeedReaction(postId: PostId, emoji: string): Promise<void>;
    addReaction(messageId: MessageId, emoji: string): Promise<void>;
    addReply(postId: PostId, input: SendFeedMediaInput): Promise<Post>;
    createCatalogRoom(title: string, description: string, coverImageUrl: string | null): Promise<CatalogRoom>;
    createDirectConversation(otherUserId: UserId): Promise<ConversationSummary>;
    createGroupConversation(name: string, memberIds: Array<UserId>): Promise<ConversationSummary>;
    createPost(input: SendFeedMediaInput): Promise<Post>;
    deleteCatalogMessage(roomId: RoomId, messageId: MessageId): Promise<void>;
    deleteMessage(messageId: MessageId): Promise<boolean>;
    deletePost(postId: PostId): Promise<void>;
    editCatalogMessage(roomId: RoomId, messageId: MessageId, newText: string): Promise<void>;
    editMessage(messageId: MessageId, newContent: MessageContent): Promise<void>;
    getCatalogMessages(roomId: RoomId, beforeId: MessageId | null): Promise<Array<CatalogMessage>>;
    getCatalogRoom(roomId: RoomId): Promise<CatalogRoom | null>;
    getCatalogRooms(search: string | null): Promise<Array<CatalogRoom>>;
    getCatalogTypingUsers(roomId: RoomId): Promise<Array<UserId>>;
    getConversation(conversationId: ConversationId): Promise<ConversationSummary | null>;
    getEditHistory(messageId: MessageId): Promise<Array<EditEntry>>;
    getFeedPosts(offset: bigint, limit: bigint): Promise<FeedPage>;
    getFeedTypingUsers(postId: PostId): Promise<Array<UserId>>;
    getJoinedCatalogRooms(): Promise<Array<CatalogRoom>>;
    getMessages(conversationId: ConversationId, beforeId: MessageId | null, limit: bigint): Promise<MessagePage>;
    getOrCreateProfile(displayName: string): Promise<UserProfile>;
    getPinnedCatalogMessages(roomId: RoomId): Promise<Array<CatalogMessage>>;
    getPinnedFeedReplies(postId: PostId): Promise<Array<Post>>;
    getPinnedMessages(conversationId: ConversationId): Promise<Array<PinnedMessage>>;
    getPostLikes(postId: PostId): Promise<Array<UserId>>;
    getPostReplies(postId: PostId): Promise<Array<Post>>;
    getProfile(userId: UserId): Promise<UserProfile | null>;
    getReactions(messageId: MessageId): Promise<Array<ReactionGroup>>;
    getSharedConversations(targetUserId: UserId): Promise<Array<ConversationSummary>>;
    getTypingUsers(conversationId: ConversationId): Promise<Array<UserProfile>>;
    getUnreadCatalogCount(roomId: RoomId): Promise<bigint>;
    getUnreadFeedCount(): Promise<bigint>;
    joinCatalogRoom(roomId: RoomId): Promise<void>;
    leaveCatalogRoom(roomId: RoomId): Promise<void>;
    likePost(postId: PostId): Promise<void>;
    listConversations(): Promise<Array<ConversationSummary>>;
    markCatalogRoomRead(roomId: RoomId): Promise<void>;
    markConversationRead(conversationId: ConversationId): Promise<void>;
    markFeedRead(): Promise<void>;
    pinCatalogMessage(roomId: RoomId, messageId: MessageId): Promise<void>;
    pinFeedReply(postId: PostId, replyId: PostId): Promise<void>;
    pinMessage(messageId: MessageId): Promise<void>;
    removeCatalogReaction(roomId: RoomId, messageId: MessageId, emoji: string): Promise<void>;
    removeFeedReaction(postId: PostId, emoji: string): Promise<void>;
    removeReaction(messageId: MessageId): Promise<void>;
    removeUserFromCatalogRoom(roomId: RoomId, userId: Principal): Promise<void>;
    reportCatalogRoom(roomId: RoomId, reason: string): Promise<void>;
    searchMessages(keyword: string): Promise<Array<SearchResult>>;
    sendCatalogMediaMessage(input: SendCatalogMediaInput): Promise<CatalogMessage>;
    sendMediaMessage(input: SendMessageInput): Promise<Message>;
    sendMessage(conversationId: ConversationId, text: string): Promise<Message>;
    setCatalogTyping(roomId: RoomId): Promise<void>;
    setFeedTyping(postId: PostId): Promise<void>;
    setTyping(conversationId: ConversationId, isTyping: boolean): Promise<void>;
    unlikePost(postId: PostId): Promise<void>;
    unpinCatalogMessage(roomId: RoomId, messageId: MessageId): Promise<void>;
    unpinFeedReply(postId: PostId, replyId: PostId): Promise<void>;
    unpinMessage(messageId: MessageId): Promise<void>;
    updateProfile(req: UpdateProfileRequest): Promise<UpdateProfileResult>;
}
import type { AudioContent as _AudioContent, CatalogMessage as _CatalogMessage, CatalogRoom as _CatalogRoom, ConversationId as _ConversationId, ConversationKind as _ConversationKind, ConversationSummary as _ConversationSummary, EditEntry as _EditEntry, FeedPage as _FeedPage, ImageContent as _ImageContent, LinkContent as _LinkContent, Message as _Message, MessageContent as _MessageContent, MessageId as _MessageId, MessagePage as _MessagePage, PinnedMessage as _PinnedMessage, Post as _Post, PostId as _PostId, RoomId as _RoomId, SendCatalogMediaInput as _SendCatalogMediaInput, SendFeedMediaInput as _SendFeedMediaInput, SendMessageInput as _SendMessageInput, Timestamp as _Timestamp, UpdateProfileRequest as _UpdateProfileRequest, UpdateProfileResult as _UpdateProfileResult, UserId as _UserId, UserProfile as _UserProfile, VideoContent as _VideoContent } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async addCatalogReaction(arg0: RoomId, arg1: MessageId, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCatalogReaction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCatalogReaction(arg0, arg1, arg2);
            return result;
        }
    }
    async addFeedReaction(arg0: PostId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFeedReaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFeedReaction(arg0, arg1);
            return result;
        }
    }
    async addReaction(arg0: MessageId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReaction(arg0, arg1);
            return result;
        }
    }
    async addReply(arg0: PostId, arg1: SendFeedMediaInput): Promise<Post> {
        if (this.processError) {
            try {
                const result = await this.actor.addReply(arg0, to_candid_SendFeedMediaInput_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Post_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReply(arg0, to_candid_SendFeedMediaInput_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Post_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCatalogRoom(arg0: string, arg1: string, arg2: string | null): Promise<CatalogRoom> {
        if (this.processError) {
            try {
                const result = await this.actor.createCatalogRoom(arg0, arg1, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2));
                return from_candid_CatalogRoom_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCatalogRoom(arg0, arg1, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2));
            return from_candid_CatalogRoom_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDirectConversation(arg0: UserId): Promise<ConversationSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.createDirectConversation(arg0);
                return from_candid_ConversationSummary_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDirectConversation(arg0);
            return from_candid_ConversationSummary_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async createGroupConversation(arg0: string, arg1: Array<UserId>): Promise<ConversationSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroupConversation(arg0, arg1);
                return from_candid_ConversationSummary_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroupConversation(arg0, arg1);
            return from_candid_ConversationSummary_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPost(arg0: SendFeedMediaInput): Promise<Post> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(to_candid_SendFeedMediaInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Post_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(to_candid_SendFeedMediaInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Post_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCatalogMessage(arg0: RoomId, arg1: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCatalogMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCatalogMessage(arg0, arg1);
            return result;
        }
    }
    async deleteMessage(arg0: MessageId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0);
            return result;
        }
    }
    async deletePost(arg0: PostId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async editCatalogMessage(arg0: RoomId, arg1: MessageId, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editCatalogMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editCatalogMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async editMessage(arg0: MessageId, arg1: MessageContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editMessage(arg0, to_candid_MessageContent_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editMessage(arg0, to_candid_MessageContent_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCatalogMessages(arg0: RoomId, arg1: MessageId | null): Promise<Array<CatalogMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCatalogMessages(arg0, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCatalogMessages(arg0, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCatalogRoom(arg0: RoomId): Promise<CatalogRoom | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCatalogRoom(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCatalogRoom(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCatalogRooms(arg0: string | null): Promise<Array<CatalogRoom>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCatalogRooms(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCatalogRooms(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCatalogTypingUsers(arg0: RoomId): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCatalogTypingUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCatalogTypingUsers(arg0);
            return result;
        }
    }
    async getConversation(arg0: ConversationId): Promise<ConversationSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEditHistory(arg0: MessageId): Promise<Array<EditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEditHistory(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEditHistory(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeedPosts(arg0: bigint, arg1: bigint): Promise<FeedPage> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedPosts(arg0, arg1);
                return from_candid_FeedPage_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedPosts(arg0, arg1);
            return from_candid_FeedPage_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeedTypingUsers(arg0: PostId): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedTypingUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedTypingUsers(arg0);
            return result;
        }
    }
    async getJoinedCatalogRooms(): Promise<Array<CatalogRoom>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJoinedCatalogRooms();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJoinedCatalogRooms();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: ConversationId, arg1: MessageId | null, arg2: bigint): Promise<MessagePage> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_MessagePage_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_MessagePage_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrCreateProfile(arg0: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrCreateProfile(arg0);
                return from_candid_UserProfile_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrCreateProfile(arg0);
            return from_candid_UserProfile_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPinnedCatalogMessages(arg0: RoomId): Promise<Array<CatalogMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPinnedCatalogMessages(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPinnedCatalogMessages(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPinnedFeedReplies(arg0: PostId): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPinnedFeedReplies(arg0);
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPinnedFeedReplies(arg0);
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPinnedMessages(arg0: ConversationId): Promise<Array<PinnedMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPinnedMessages(arg0);
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPinnedMessages(arg0);
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostLikes(arg0: PostId): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostLikes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostLikes(arg0);
            return result;
        }
    }
    async getPostReplies(arg0: PostId): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostReplies(arg0);
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostReplies(arg0);
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReactions(arg0: MessageId): Promise<Array<ReactionGroup>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReactions(arg0);
            return result;
        }
    }
    async getSharedConversations(arg0: UserId): Promise<Array<ConversationSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSharedConversations(arg0);
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSharedConversations(arg0);
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTypingUsers(arg0: ConversationId): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTypingUsers(arg0);
                return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTypingUsers(arg0);
            return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadCatalogCount(arg0: RoomId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCatalogCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCatalogCount(arg0);
            return result;
        }
    }
    async getUnreadFeedCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadFeedCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadFeedCount();
            return result;
        }
    }
    async joinCatalogRoom(arg0: RoomId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinCatalogRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinCatalogRoom(arg0);
            return result;
        }
    }
    async leaveCatalogRoom(arg0: RoomId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveCatalogRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveCatalogRoom(arg0);
            return result;
        }
    }
    async likePost(arg0: PostId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async listConversations(): Promise<Array<ConversationSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listConversations();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listConversations();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async markCatalogRoomRead(arg0: RoomId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markCatalogRoomRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markCatalogRoomRead(arg0);
            return result;
        }
    }
    async markConversationRead(arg0: ConversationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markConversationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markConversationRead(arg0);
            return result;
        }
    }
    async markFeedRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markFeedRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markFeedRead();
            return result;
        }
    }
    async pinCatalogMessage(arg0: RoomId, arg1: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pinCatalogMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pinCatalogMessage(arg0, arg1);
            return result;
        }
    }
    async pinFeedReply(arg0: PostId, arg1: PostId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pinFeedReply(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pinFeedReply(arg0, arg1);
            return result;
        }
    }
    async pinMessage(arg0: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pinMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pinMessage(arg0);
            return result;
        }
    }
    async removeCatalogReaction(arg0: RoomId, arg1: MessageId, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCatalogReaction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCatalogReaction(arg0, arg1, arg2);
            return result;
        }
    }
    async removeFeedReaction(arg0: PostId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFeedReaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFeedReaction(arg0, arg1);
            return result;
        }
    }
    async removeReaction(arg0: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeReaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeReaction(arg0);
            return result;
        }
    }
    async removeUserFromCatalogRoom(arg0: RoomId, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUserFromCatalogRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUserFromCatalogRoom(arg0, arg1);
            return result;
        }
    }
    async reportCatalogRoom(arg0: RoomId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportCatalogRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportCatalogRoom(arg0, arg1);
            return result;
        }
    }
    async searchMessages(arg0: string): Promise<Array<SearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMessages(arg0);
            return result;
        }
    }
    async sendCatalogMediaMessage(arg0: SendCatalogMediaInput): Promise<CatalogMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.sendCatalogMediaMessage(to_candid_SendCatalogMediaInput_n64(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CatalogMessage_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendCatalogMediaMessage(to_candid_SendCatalogMediaInput_n64(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CatalogMessage_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMediaMessage(arg0: SendMessageInput): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMediaMessage(to_candid_SendMessageInput_n66(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Message_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMediaMessage(to_candid_SendMessageInput_n66(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Message_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: ConversationId, arg1: string): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return from_candid_Message_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return from_candid_Message_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async setCatalogTyping(arg0: RoomId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCatalogTyping(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCatalogTyping(arg0);
            return result;
        }
    }
    async setFeedTyping(arg0: PostId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFeedTyping(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFeedTyping(arg0);
            return result;
        }
    }
    async setTyping(arg0: ConversationId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTyping(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTyping(arg0, arg1);
            return result;
        }
    }
    async unlikePost(arg0: PostId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return result;
        }
    }
    async unpinCatalogMessage(arg0: RoomId, arg1: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unpinCatalogMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpinCatalogMessage(arg0, arg1);
            return result;
        }
    }
    async unpinFeedReply(arg0: PostId, arg1: PostId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unpinFeedReply(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpinFeedReply(arg0, arg1);
            return result;
        }
    }
    async unpinMessage(arg0: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unpinMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpinMessage(arg0);
            return result;
        }
    }
    async updateProfile(arg0: UpdateProfileRequest): Promise<UpdateProfileResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_UpdateProfileRequest_n68(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UpdateProfileResult_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_UpdateProfileRequest_n68(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UpdateProfileResult_n70(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AudioContent_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AudioContent): AudioContent {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_CatalogMessage_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CatalogMessage): CatalogMessage {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_CatalogRoom_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CatalogRoom): CatalogRoom {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ConversationKind_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConversationKind): ConversationKind {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_ConversationSummary_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConversationSummary): ConversationSummary {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_EditEntry_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EditEntry): EditEntry {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_FeedPage_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedPage): FeedPage {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_ImageContent_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImageContent): ImageContent {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_LinkContent_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LinkContent): LinkContent {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_MessageContent_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageContent): MessageContent {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_MessagePage_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessagePage): MessagePage {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_PinnedMessage_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PinnedMessage): PinnedMessage {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_Post_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Post {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UpdateProfileResult_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpdateProfileResult): UpdateProfileResult {
    return from_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_VideoContent_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoContent): VideoContent {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PostId]): PostId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CatalogRoom]): CatalogRoom | null {
    return value.length === 0 ? null : from_candid_CatalogRoom_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ConversationSummary]): ConversationSummary | null {
    return value.length === 0 ? null : from_candid_ConversationSummary_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MessageId]): MessageId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n55(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PostId;
    parentPostId: [] | [_PostId];
    content: _MessageContent;
    likedBy: Array<_UserId>;
    author: _UserId;
    pinned: boolean;
    timestamp: _Timestamp;
    reactions: Array<[string, Array<_UserId>]>;
}): {
    id: PostId;
    parentPostId?: PostId;
    content: MessageContent;
    likedBy: Array<UserId>;
    author: UserId;
    pinned: boolean;
    timestamp: Timestamp;
    reactions: Array<[string, Array<UserId>]>;
} {
    return {
        id: value.id,
        parentPostId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.parentPostId)),
        content: from_candid_MessageContent_n16(_uploadFile, _downloadFile, value.content),
        likedBy: value.likedBy,
        author: value.author,
        pinned: value.pinned,
        timestamp: value.timestamp,
        reactions: value.reactions
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    duration: [] | [bigint];
    mimeType: string;
    fileSize: bigint;
}): {
    url: string;
    duration?: bigint;
    mimeType: string;
    fileSize: bigint;
} {
    return {
        url: value.url,
        duration: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.duration)),
        mimeType: value.mimeType,
        fileSize: value.fileSize
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    duration: [] | [bigint];
    thumbnailUrl: [] | [string];
    mimeType: string;
    fileSize: bigint;
}): {
    url: string;
    duration?: bigint;
    thumbnailUrl?: string;
    mimeType: string;
    fileSize: bigint;
} {
    return {
        url: value.url,
        duration: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.duration)),
        thumbnailUrl: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.thumbnailUrl)),
        mimeType: value.mimeType,
        fileSize: value.fileSize
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    title: [] | [string];
    description: [] | [string];
    imageUrl: [] | [string];
}): {
    url: string;
    title?: string;
    description?: string;
    imageUrl?: string;
} {
    return {
        url: value.url,
        title: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.title)),
        description: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.description)),
        imageUrl: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.imageUrl))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    height: [] | [bigint];
    mimeType: string;
    fileSize: bigint;
    width: [] | [bigint];
}): {
    url: string;
    height?: bigint;
    mimeType: string;
    fileSize: bigint;
    width?: bigint;
} {
    return {
        url: value.url,
        height: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.height)),
        mimeType: value.mimeType,
        fileSize: value.fileSize,
        width: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.width))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RoomId;
    coverImageUrl: [] | [string];
    title: string;
    creator: _UserId;
    members: Array<_UserId>;
    createdAt: _Timestamp;
    description: string;
    messageCount: bigint;
    lastActivityAt: _Timestamp;
}): {
    id: RoomId;
    coverImageUrl?: string;
    title: string;
    creator: UserId;
    members: Array<UserId>;
    createdAt: Timestamp;
    description: string;
    messageCount: bigint;
    lastActivityAt: Timestamp;
} {
    return {
        id: value.id,
        coverImageUrl: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.coverImageUrl)),
        title: value.title,
        creator: value.creator,
        members: value.members,
        createdAt: value.createdAt,
        description: value.description,
        messageCount: value.messageCount,
        lastActivityAt: value.lastActivityAt
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ConversationId;
    members: Array<_UserId>;
    lastMessageAt: [] | [_Timestamp];
    kind: _ConversationKind;
    unreadCount: bigint;
}): {
    id: ConversationId;
    members: Array<UserId>;
    lastMessageAt?: Timestamp;
    kind: ConversationKind;
    unreadCount: bigint;
} {
    return {
        id: value.id,
        members: value.members,
        lastMessageAt: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.lastMessageAt)),
        kind: from_candid_ConversationKind_n34(_uploadFile, _downloadFile, value.kind),
        unreadCount: value.unreadCount
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    deleted: boolean;
    content: _MessageContent;
    createdAt: _Timestamp;
    author: _UserId;
    pinned: boolean;
    roomId: _RoomId;
    editedAt: [] | [_Timestamp];
    reactions: Array<[string, Array<_UserId>]>;
}): {
    id: MessageId;
    deleted: boolean;
    content: MessageContent;
    createdAt: Timestamp;
    author: UserId;
    pinned: boolean;
    roomId: RoomId;
    editedAt?: Timestamp;
    reactions: Array<[string, Array<UserId>]>;
} {
    return {
        id: value.id,
        deleted: value.deleted,
        content: from_candid_MessageContent_n16(_uploadFile, _downloadFile, value.content),
        createdAt: value.createdAt,
        author: value.author,
        pinned: value.pinned,
        roomId: value.roomId,
        editedAt: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.editedAt)),
        reactions: value.reactions
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    editedAt: _Timestamp;
    previousContent: _MessageContent;
}): {
    editedAt: Timestamp;
    previousContent: MessageContent;
} {
    return {
        editedAt: value.editedAt,
        previousContent: from_candid_MessageContent_n16(_uploadFile, _downloadFile, value.previousContent)
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    posts: Array<_Post>;
}): {
    total: bigint;
    posts: Array<Post>;
} {
    return {
        total: value.total,
        posts: from_candid_vec_n48(_uploadFile, _downloadFile, value.posts)
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    messages: Array<_Message>;
    nextCursor: [] | [_MessageId];
}): {
    messages: Array<Message>;
    nextCursor?: MessageId;
} {
    return {
        messages: from_candid_vec_n51(_uploadFile, _downloadFile, value.messages),
        nextCursor: record_opt_to_undefined(from_candid_opt_n54(_uploadFile, _downloadFile, value.nextCursor))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    content: _MessageContent;
    sender: _UserId;
    sentAt: _Timestamp;
    conversationId: _ConversationId;
}): {
    id: MessageId;
    content: MessageContent;
    sender: UserId;
    sentAt: Timestamp;
    conversationId: ConversationId;
} {
    return {
        id: value.id,
        content: from_candid_MessageContent_n16(_uploadFile, _downloadFile, value.content),
        sender: value.sender,
        sentAt: value.sentAt,
        conversationId: value.conversationId
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: [] | [string];
    displayName: string;
    lastHandleChange: [] | [bigint];
    registeredAt: _Timestamp;
    usernameHandle: [] | [string];
    profileImageUrl: [] | [string];
}): {
    id: UserId;
    bio?: string;
    displayName: string;
    lastHandleChange?: bigint;
    registeredAt: Timestamp;
    usernameHandle?: string;
    profileImageUrl?: string;
} {
    return {
        id: value.id,
        bio: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.bio)),
        displayName: value.displayName,
        lastHandleChange: record_opt_to_undefined(from_candid_opt_n57(_uploadFile, _downloadFile, value.lastHandleChange)),
        registeredAt: value.registeredAt,
        usernameHandle: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.usernameHandle)),
        profileImageUrl: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.profileImageUrl))
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    messageId: _MessageId;
    conversationId: _ConversationId;
    message: _Message;
    pinnedAt: _Timestamp;
    pinnedBy: _UserId;
}): {
    messageId: MessageId;
    conversationId: ConversationId;
    message: Message;
    pinnedAt: Timestamp;
    pinnedBy: UserId;
} {
    return {
        messageId: value.messageId,
        conversationId: value.conversationId,
        message: from_candid_Message_n52(_uploadFile, _downloadFile, value.message),
        pinnedAt: value.pinnedAt,
        pinnedBy: value.pinnedBy
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deleted: null;
} | {
    audio: _AudioContent;
} | {
    video: _VideoContent;
} | {
    link: _LinkContent;
} | {
    text: string;
} | {
    image: _ImageContent;
}): {
    __kind__: "deleted";
    deleted: null;
} | {
    __kind__: "audio";
    audio: AudioContent;
} | {
    __kind__: "video";
    video: VideoContent;
} | {
    __kind__: "link";
    link: LinkContent;
} | {
    __kind__: "text";
    text: string;
} | {
    __kind__: "image";
    image: ImageContent;
} {
    return "deleted" in value ? {
        __kind__: "deleted",
        deleted: value.deleted
    } : "audio" in value ? {
        __kind__: "audio",
        audio: from_candid_AudioContent_n18(_uploadFile, _downloadFile, value.audio)
    } : "video" in value ? {
        __kind__: "video",
        video: from_candid_VideoContent_n21(_uploadFile, _downloadFile, value.video)
    } : "link" in value ? {
        __kind__: "link",
        link: from_candid_LinkContent_n24(_uploadFile, _downloadFile, value.link)
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : "image" in value ? {
        __kind__: "image",
        image: from_candid_ImageContent_n26(_uploadFile, _downloadFile, value.image)
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    group: {
        name: string;
    };
} | {
    direct: null;
}): {
    __kind__: "group";
    group: {
        name: string;
    };
} | {
    __kind__: "direct";
    direct: null;
} {
    return "group" in value ? {
        __kind__: "group",
        group: value.group
    } : "direct" in value ? {
        __kind__: "direct",
        direct: value.direct
    } : value;
}
function from_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n55(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CatalogMessage>): Array<CatalogMessage> {
    return value.map((x)=>from_candid_CatalogMessage_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CatalogRoom>): Array<CatalogRoom> {
    return value.map((x)=>from_candid_CatalogRoom_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EditEntry>): Array<EditEntry> {
    return value.map((x)=>from_candid_EditEntry_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Array<Post> {
    return value.map((x)=>from_candid_Post_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PinnedMessage>): Array<PinnedMessage> {
    return value.map((x)=>from_candid_PinnedMessage_n59(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConversationSummary>): Array<ConversationSummary> {
    return value.map((x)=>from_candid_ConversationSummary_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n55(_uploadFile, _downloadFile, x));
}
function to_candid_AudioContent_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudioContent): _AudioContent {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_ImageContent_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImageContent): _ImageContent {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_LinkContent_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LinkContent): _LinkContent {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_MessageContent_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageContent): _MessageContent {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SendCatalogMediaInput_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SendCatalogMediaInput): _SendCatalogMediaInput {
    return to_candid_record_n65(_uploadFile, _downloadFile, value);
}
function to_candid_SendFeedMediaInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SendFeedMediaInput): _SendFeedMediaInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_SendMessageInput_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SendMessageInput): _SendMessageInput {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProfileRequest_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProfileRequest): _UpdateProfileRequest {
    return to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid_VideoContent_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoContent): _VideoContent {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageId | null): [] | [_MessageId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    duration?: bigint;
    thumbnailUrl?: string;
    mimeType: string;
    fileSize: bigint;
}): {
    url: string;
    duration: [] | [bigint];
    thumbnailUrl: [] | [string];
    mimeType: string;
    fileSize: bigint;
} {
    return {
        url: value.url,
        duration: value.duration ? candid_some(value.duration) : candid_none(),
        thumbnailUrl: value.thumbnailUrl ? candid_some(value.thumbnailUrl) : candid_none(),
        mimeType: value.mimeType,
        fileSize: value.fileSize
    };
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    duration?: bigint;
    mimeType: string;
    fileSize: bigint;
}): {
    url: string;
    duration: [] | [bigint];
    mimeType: string;
    fileSize: bigint;
} {
    return {
        url: value.url,
        duration: value.duration ? candid_some(value.duration) : candid_none(),
        mimeType: value.mimeType,
        fileSize: value.fileSize
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    parentPostId?: PostId;
    content: MessageContent;
}): {
    parentPostId: [] | [_PostId];
    content: _MessageContent;
} {
    return {
        parentPostId: value.parentPostId ? candid_some(value.parentPostId) : candid_none(),
        content: to_candid_MessageContent_n3(_uploadFile, _downloadFile, value.content)
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    height?: bigint;
    mimeType: string;
    fileSize: bigint;
    width?: bigint;
}): {
    url: string;
    height: [] | [bigint];
    mimeType: string;
    fileSize: bigint;
    width: [] | [bigint];
} {
    return {
        url: value.url,
        height: value.height ? candid_some(value.height) : candid_none(),
        mimeType: value.mimeType,
        fileSize: value.fileSize,
        width: value.width ? candid_some(value.width) : candid_none()
    };
}
function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: MessageContent;
    roomId: RoomId;
}): {
    content: _MessageContent;
    roomId: _RoomId;
} {
    return {
        content: to_candid_MessageContent_n3(_uploadFile, _downloadFile, value.content),
        roomId: value.roomId
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: MessageContent;
    conversationId: bigint;
}): {
    content: _MessageContent;
    conversationId: bigint;
} {
    return {
        content: to_candid_MessageContent_n3(_uploadFile, _downloadFile, value.content),
        conversationId: value.conversationId
    };
}
function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    displayName?: string;
    usernameHandle?: string;
    profileImageUrl?: string;
}): {
    bio: [] | [string];
    displayName: [] | [string];
    usernameHandle: [] | [string];
    profileImageUrl: [] | [string];
} {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        displayName: value.displayName ? candid_some(value.displayName) : candid_none(),
        usernameHandle: value.usernameHandle ? candid_some(value.usernameHandle) : candid_none(),
        profileImageUrl: value.profileImageUrl ? candid_some(value.profileImageUrl) : candid_none()
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    title?: string;
    description?: string;
    imageUrl?: string;
}): {
    url: string;
    title: [] | [string];
    description: [] | [string];
    imageUrl: [] | [string];
} {
    return {
        url: value.url,
        title: value.title ? candid_some(value.title) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "deleted";
    deleted: null;
} | {
    __kind__: "audio";
    audio: AudioContent;
} | {
    __kind__: "video";
    video: VideoContent;
} | {
    __kind__: "link";
    link: LinkContent;
} | {
    __kind__: "text";
    text: string;
} | {
    __kind__: "image";
    image: ImageContent;
}): {
    deleted: null;
} | {
    audio: _AudioContent;
} | {
    video: _VideoContent;
} | {
    link: _LinkContent;
} | {
    text: string;
} | {
    image: _ImageContent;
} {
    return value.__kind__ === "deleted" ? {
        deleted: value.deleted
    } : value.__kind__ === "audio" ? {
        audio: to_candid_AudioContent_n11(_uploadFile, _downloadFile, value.audio)
    } : value.__kind__ === "video" ? {
        video: to_candid_VideoContent_n9(_uploadFile, _downloadFile, value.video)
    } : value.__kind__ === "link" ? {
        link: to_candid_LinkContent_n7(_uploadFile, _downloadFile, value.link)
    } : value.__kind__ === "text" ? {
        text: value.text
    } : value.__kind__ === "image" ? {
        image: to_candid_ImageContent_n5(_uploadFile, _downloadFile, value.image)
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
